// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_count_table
Rcpp::XPtr<std::unordered_map<int, int>> create_count_table();
RcppExport SEXP _posDemux_create_count_table() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(create_count_table());
    return rcpp_result_gen;
END_RCPP
}
// add_table_entries
void add_table_entries(Rcpp::XPtr<std::unordered_map<int, int>> table, IntegerVector chunk);
RcppExport SEXP _posDemux_add_table_entries(SEXP tableSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<std::unordered_map<int, int>> >::type table(tableSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chunk(chunkSEXP);
    add_table_entries(table, chunk);
    return R_NilValue;
END_RCPP
}
// get_count_table
List get_count_table(Rcpp::XPtr<std::unordered_map<int, int>> table);
RcppExport SEXP _posDemux_get_count_table(SEXP tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<std::unordered_map<int, int>> >::type table(tableSEXP);
    rcpp_result_gen = Rcpp::wrap(get_count_table(table));
    return rcpp_result_gen;
END_RCPP
}
// hamming_match
List hamming_match(SEXP segment, SEXP segment_names, SEXP barcode, CharacterVector barcode_names, int width);
RcppExport SEXP _posDemux_hamming_match(SEXP segmentSEXP, SEXP segment_namesSEXP, SEXP barcodeSEXP, SEXP barcode_namesSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type segment(segmentSEXP);
    Rcpp::traits::input_parameter< SEXP >::type segment_names(segment_namesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type barcode(barcodeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type barcode_names(barcode_namesSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_match(segment, segment_names, barcode, barcode_names, width));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_posDemux_create_count_table", (DL_FUNC) &_posDemux_create_count_table, 0},
    {"_posDemux_add_table_entries", (DL_FUNC) &_posDemux_add_table_entries, 2},
    {"_posDemux_get_count_table", (DL_FUNC) &_posDemux_get_count_table, 1},
    {"_posDemux_hamming_match", (DL_FUNC) &_posDemux_hamming_match, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_posDemux(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
